theme: jekyll-theme-hacker
title: [Compubeer]
description: [Beer that thinks while you drink]
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
plugins:
  - jekyll-include-cache
include: ["_pages"] 
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
