remote_theme: "mmistakes/minimal-mistakes@4.19.3"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Site Settings
locale: "en-US"
title: "Compubeer"
description: "beer: the funnest thing you can do with computers"
url: "https://compubeer.com"
baseurl: "/"
repository: "rmwoods/beer.ai"

plugins:
  - jekyll-include-cache

include:
  - "_pages"

# Collections
collections:
  apps:
    output: true
    permalink: /:collection/:path/

# specify a default teaser image site-wide here
# teaser: /assets/images/shit-logo.png

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _apps
  - scope:
      path: ""
      type: apps
    values:
      layout: splash
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
