remote_theme: "mmistakes/minimal-mistakes@4.19.3"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Site Settings
locale: "en-US"
title: "Compubeer"
description: "Beer that thinks while you drink"
url: "https://compubeer.com"
baseurl: "/"
repository: "rmwoods/beer.ai"

plugins:
  - jekyll-include-cache


include:
  - "_pages"

# Collections
collections:
  apps:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: false
  # _apps
  - scope:
      path: ""
      type: apps
    values:
      layout: single
      sidebar: false
      read_time: false
      comments: false
      share: true
      related: false
